"""Add categoria to Producto

Revision ID: 50131f513857
Revises: 629b0366ae1d
Create Date: 2024-11-03 15:00:13.796899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50131f513857'
down_revision = '629b0366ae1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
